PlatformDemonList/urls.py
"""PlatformDemonList URLs module."""

# Django
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.urls import path, re_path, include, reverse_lazy
from django.views.static import serve

# Views
from PlatformDemonList import views
from apps.demonlist.views.views import custom_404_view

# Forms
from apps.users import forms

urlpatterns = [

    path('admin/', admin.site.urls),
    path('ads.txt', serve, {'document_root': settings.BASE_DIR, 'path': 'ads.txt'}),

    path("users/", include(("apps.users.urls", "users"), namespace="users")),
    path('accounts/', include('allauth.urls')),

    re_path(
        route=r'^reset_password/?$',
        view=views.CustomPasswordResetView.as_view(),
        name='reset_password'
    ),
    re_path(
        route=r'^reset_password_sent/?$',
        view=views.CustomPasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    re_path(
        route=r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/?$',
        view=views.CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    re_path(
        route=r'^reset_password_complete/?$',
        view=views.CustomPasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    re_path(
        route=r'^reset_email/?$',
        view=views.CustomEmailResetView.as_view(),
        name='reset_email'
    ),
    re_path(
        route=r'^reset_email_sent/?$',
        view=views.CustomEmailResetDoneView.as_view(),
        name='email_reset_done'
    ),
    re_path(
        route=r'^reset_email/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/?$',
        view=views.CustomEmailResetConfirmView.as_view(),
        name='email_reset_confirm'
    ),
    re_path(
        route=r'^reset_email_complete/?$',
        view=views.CustomEmailResetCompleteView.as_view(),
        name='email_reset_complete'
    ),
    re_path(
        route=r'^terms/?$',
        view=views.TermsView.as_view(),
        name='terms'
    ),

    re_path(
        route=r'^guidelines/?$',
        view=views.GuidelinesView.as_view(),
        name='guidelines'
    ),

    re_path(
        route=r'^credits/?$',
        view=views.CreditsView.as_view(),
        name='credits'
    ),
    re_path(
        route=r'^settings/?$',
        view=views.SettingsView.as_view(),
        name='settings'
    ),

    path('', include(('apps.demonlist.urls', 'demonlist'), namespace='demonlist')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404_view

apps/users/urls.py
# Django
from django.urls import path, re_path

# View
from apps.users.views import views, views_discord


urlpatterns = [

    # Management
    re_path(
        route=r'^oauth2/login/?$',
        view=views_discord.discord_login,
        name='discord_login'
    ),
    re_path(
        route=r'^oauth2/login/redirect/?$',
        view=views_discord.DiscordLoginRedirectView.as_view(),
        name='discord_login_redirect'
    ),
    re_path(
        route=r'^update_account/?$',
        view=views_discord.UpdateAccount.as_view(),
        name='update_account'
    ),
    re_path(
        route=r'^demo_recaptcha/?$',
        view=views.demo_recaptcha,
        name='demo_recaptcha'
    ),
    re_path(
        route=r'^read_notifications/?$',
        view=views.ReadNotifications.as_view(),
        name='read_notifications'
    ),
    re_path(
        route=r'^login/?$',
        view=views.LoginView.as_view(),
        name='login'
    ),
    re_path(
        route=r'^logout/?$',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    re_path(
        route=r'^signup/?$',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    re_path(
        route=r'^me/?$',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),
    re_path(
        route=r'^me/teams/?$',
        view=views.TeamsView.as_view(),
        name='teams'
    ),
    re_path(
        route=r'^me/records_status/?$',
        view=views.RecordsStatusView.as_view(),
        name='records_status'
    ),

    # Rutas con expresión regular

    re_path(
        route=r'^(?P<user>\d+)/?$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

templates/users/reset/email_reset/email_reset.html
{% extends "users/base.html" %}
{% load static %}

{% block head_content %}
    <title>{{list_words.reset_email}}</title>
    <link rel="stylesheet" href="{% static 'css/password_reset.css' %}?v=1.24">
{% endblock  %}

{% block container %}

<form class="reset-password-form" method="POST">

    {% csrf_token %}

    <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.want_to_change}}</p>

    {{form.as_p}}

    <button type="submit" class="reset-password-button main-button-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.send_email}}</button>

</form>

<script>

    function without_space(e){
        e.value = e.value.replace(/ /g, '')
    }
</script>
{% endblock  %}

templates/users/reset/email_reset/email_reset_complete.html
{% extends "users/base.html" %}
{% load static %}

{% block head_content %}
    <title>{{list_words.reset_email}}</title>
    <link rel="stylesheet" href="{% static 'css/password_reset.css' %}?v=1.24">
{% endblock  %}

{% block container %}

<form class="reset-password-form" method="POST">
    {% csrf_token %}

    <h4 class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.email_reset_complete}}</h4>

    <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.your_email_has_been_set}}{% if request.user.is_anonymous %} You may go ahead and log in now.{% endif %}</p>

    {% if request.user.is_anonymous %}
    <div class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
        <a href="{% url 'users:login' %}" class="reset-password-button main-button-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">Log in</a>
    </div>
    {% endif %}

</form>
<script>

    function without_space(e){
        e.value = e.value.replace(/ /g, '')
    }
</script>
{% endblock  %}

templates/users/reset/email_reset/email_reset_confirm.html
{% extends "users/base.html" %}
{% load static %}

{% block head_content %}
    <title>{{list_words.reset_email}}</title>
    <link rel="stylesheet" href="{% static 'css/password_reset.css' %}?v=1.24">
{% endblock  %}

{% block container %}


{% if validlink %}

<form class="reset-password-form" method="POST">
    {% csrf_token %}

    <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.please_enter_your_new_email}}</p>

    {% if form.email.errors %}
        {% for error in form.email.errors %}
            <div>
                <li class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode"><i class="fas fa-exclamation-triangle"></i> {{ error }}</li>
            </div>
        {% endfor %}
    {% endif %}
    
    {{ form.new_email }}

    <div>
        <button class="reset-password-button" type="submit">{{list_words.change_my_email}}</button>
    </div>

</form>

{% else %}

<p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.the_email_reset_link_was_invalid}}</p>

{% endif %}

<script>

    function without_space(e){
        e.value = e.value.replace(/ /g, '')
    }
</script>
{% endblock  %}

templates/users/reset/email_reset/email_reset_done.html
{% extends "users/base.html" %}
{% load static %}

{% block head_content %}
    <title>{{list_words.reset_email}}</title>
    <link rel="stylesheet" href="{% static 'css/password_reset.css' %}?v=1.24">
{% endblock  %}

{% block container %}

<form class="reset-password-form" method="POST">
    {% csrf_token %}

    <h4 class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.email_reset_sent}}</h4>

    <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.we_emailed_instructions}}</p>

    <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.if_you_dont_receive}}</p>

</form>
<script>

    function without_space(e){
        e.value = e.value.replace(/ /g, '')
    }
</script>
{% endblock  %}