PlatformDemonList/urls.py
"""PlatformDemonList URLs module."""

# Django
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.urls import path, re_path, include, reverse_lazy
from django.views.static import serve

# Views
from PlatformDemonList import views
from apps.demonlist.views.views import custom_404_view

# Forms
from apps.users import forms

urlpatterns = [

    path('admin/', admin.site.urls),
    path('ads.txt', serve, {'document_root': settings.BASE_DIR, 'path': 'ads.txt'}),

    path("users/", include(("apps.users.urls", "users"), namespace="users")),
    path('accounts/', include('allauth.urls')),

    re_path(
        route=r'^reset_password/?$',
        view=views.CustomPasswordResetView.as_view(),
        name='reset_password'
    ),
    re_path(
        route=r'^reset_password_sent/?$',
        view=views.CustomPasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    re_path(
        route=r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/?$',
        view=views.CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    re_path(
        route=r'^reset_password_complete/?$',
        view=views.CustomPasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    re_path(
        route=r'^reset_email/?$',
        view=views.CustomEmailResetView.as_view(),
        name='reset_email'
    ),
    re_path(
        route=r'^reset_email_sent/?$',
        view=views.CustomEmailResetDoneView.as_view(),
        name='email_reset_done'
    ),
    re_path(
        route=r'^reset_email/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/?$',
        view=views.CustomEmailResetConfirmView.as_view(),
        name='email_reset_confirm'
    ),
    re_path(
        route=r'^reset_email_complete/?$',
        view=views.CustomEmailResetCompleteView.as_view(),
        name='email_reset_complete'
    ),
    re_path(
        route=r'^terms/?$',
        view=views.TermsView.as_view(),
        name='terms'
    ),

    re_path(
        route=r'^guidelines/?$',
        view=views.GuidelinesView.as_view(),
        name='guidelines'
    ),

    re_path(
        route=r'^credits/?$',
        view=views.CreditsView.as_view(),
        name='credits'
    ),
    re_path(
        route=r'^settings/?$',
        view=views.SettingsView.as_view(),
        name='settings'
    ),

    path('', include(('apps.demonlist.urls', 'demonlist'), namespace='demonlist')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404_view

apps/demonlist/urls.py
"""DemonList URLs."""

# Django
from django.urls import path, re_path

# Views
from apps.demonlist.views import views, views_api
from PlatformDemonList import views as global_views

urlpatterns = [

    path(
        route=r'',
        view=views.HomeView.as_view(),
        name='home'
    ),
    re_path(
        route=r'^vote_stars/(?P<pk>\d+)/?$',
        view=views.VoteStarsView.as_view(),
        name='vote_stars'
    ),
    re_path(
        route=r'^roulette/(?P<pk>\d+)/?$',
        view=views.RouletteView.as_view(),
        name='roulette'
    ),
    re_path(
        route=r'^submit_record/?$',
        view=views.SubmitRecordView.as_view(),
        name='submit_record'
    ),
    re_path(
        route=r'^stats_viewer/?$',
        view=views.StatsViewerView.as_view(),
        name='stats_viewer'
    ),
    re_path(
        route=r'^check_records/?$',
        view=views.CheckRecordsView.as_view(),
        name='check_records'
    ),
    re_path(
        route=r'^check_profiles/?$',
        view=views.CheckProfilesView.as_view(),
        name='check_profiles'
    ),
    re_path(
        route=r'^add_edit_demon/?$',
        view=views.AddEditDemonView.as_view(),
        name='add_edit_demon'
    ),
    re_path(
        route=r'^add_edit_profile/?$',
        view=views.AddEditProfileView.as_view(),
        name='add_edit_profile'
    ),
    re_path(
        route=r'^roulette/?$',
        view=views.CreateRouletteView.as_view(),
        name='create_roulette'
    ),
    re_path(
        route=r'^roulette_menu/?$',
        view=views.RouletteMenuView.as_view(),
        name='roulette_menu'
    ),
    re_path(
        route=r'^diary_role/?$',
        view=views.DiaryRole.as_view(),
        name='diary_role'
    ),
    re_path(
        route=r'^change_language/?$',
        view=views.change_language,
        name='change_language'
    ),

    # API

    re_path(
        route=r'^api/level/?$',
        view=views_api.DemonApi.as_view(),
        name='demon_api'
    ),

    # Rutas con expresión regular

    re_path(
        route=r'^id/(?P<level_id>\d+)/?$',
        view=views.DemonDetailView.as_view(),
        name='level_id_detail'
    ),
    re_path(
        route=r'^(?P<category>\w+)/(?P<position>\d+)/?$',
        view=views.DemonDetailView.as_view(),
        name='detail'
    ),
    re_path(
        route=r'^(?P<category>\w+)/level_packs/?$',
        view=views.LevelPacksView.as_view(),
        name='level_packs'
    ),
    re_path(
        route=r'^(?P<mode>\w+)/(?P<category>\w+)/?$',
        view=views.DemonListView.as_view(),
        name='list'
    ),
    re_path(
        route=r'^(?P<mode>\w+)/(?P<category>\w+)/legacy/?$',
        view=views.DemonListView.as_view(),
        name='list_legacy'
    ),
    re_path(
        route=r'^(?P<mode>\w+)/(?P<category>\w+)/level_packs/?$',
        view=views.LevelPacksView.as_view(),
        name='level_packs'
    ),
    re_path(
        route=r'^(?P<mode>\w+)/(?P<category>\w+)/(?P<position>\d+)/?$',
        view=views.DemonDetailView.as_view(),
        name='detail'
    ),
    re_path(
        route=r'^(?P<value>[^/]+)/?$',
        view=views.CategoryOrUsernameView.as_view(),
        name='category_or_username'
    ),
]

apps/users/urls.py
# Django
from django.urls import path, re_path

# View
from apps.users.views import views, views_discord


urlpatterns = [

    # Management
    re_path(
        route=r'^oauth2/login/?$',
        view=views_discord.discord_login,
        name='discord_login'
    ),
    re_path(
        route=r'^oauth2/login/redirect/?$',
        view=views_discord.DiscordLoginRedirectView.as_view(),
        name='discord_login_redirect'
    ),
    re_path(
        route=r'^update_account/?$',
        view=views_discord.UpdateAccount.as_view(),
        name='update_account'
    ),
    re_path(
        route=r'^demo_recaptcha/?$',
        view=views.demo_recaptcha,
        name='demo_recaptcha'
    ),
    re_path(
        route=r'^read_notifications/?$',
        view=views.ReadNotifications.as_view(),
        name='read_notifications'
    ),
    re_path(
        route=r'^login/?$',
        view=views.LoginView.as_view(),
        name='login'
    ),
    re_path(
        route=r'^logout/?$',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    re_path(
        route=r'^signup/?$',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    re_path(
        route=r'^me/?$',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),
    re_path(
        route=r'^me/teams/?$',
        view=views.TeamsView.as_view(),
        name='teams'
    ),
    re_path(
        route=r'^me/records_status/?$',
        view=views.RecordsStatusView.as_view(),
        name='records_status'
    ),

    # Rutas con expresión regular

    re_path(
        route=r'^(?P<user>\d+)/?$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PlatformerWorld</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <!-- Add Sortable.js -->
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"></script>
</head>

<body>
    <canvas id="particleCanvas"></canvas>

    {% include "nav.html" %}

    {% block container %}
    {% endblock%}

    <footer>
        <p>&copy; 2024 PlatformerWorld - Creado por Chenii y el Chucky</p>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/countdown.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>Coming Soon</title>
{% endblock%}

{% block container %}

<main class="bg-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
    <div id="cube-icon-container-left" class="left-bg"></div>
        <article class="text-countdown-container">
            <h2 class="text-coming-soon">DEMONLIST UPDATE 1.2</h2>
            <h2 class="text-coming-soon">COMING SOON!</h2>
        </article>
    <div id="cube-icon-container-right" class="right-bg"></div>
</main>

{% endblock %}

templates/countdown_chido.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>Countdown</title>
{% endblock%}

{% block container %}

<main class="bg-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
    <div id="cube-icon-container-left" class="left-bg"></div>
    <article class="text-countdown-container">
                <h2 class="text-countdown" id="countdown">{{ data.hours|stringformat:"02d" }} : {{ data.minutes|stringformat:"02d" }} : {{ data.seconds|stringformat:"02d" }}</h2>
                <h2 class="second-text-countdown">ENTRA A NUESTRO VIDEO DE ESTRENO!!!!!</h2>
                <iframe src="https://www.youtube.com/embed/mBMp_Raw7T4" frameborder="0" width="1000" height="562.5" class="second-text-countdown"></iframe>
        </article>
    <div id="cube-icon-container-right" class="right-bg"></div>
</main>

<script>
    // Function to update the countdown timer
    function updateTimer() {
        var hours = parseInt(document.getElementById('countdown').textContent.split(':')[0]);
        var minutes = parseInt(document.getElementById('countdown').textContent.split(':')[1]);
        var seconds = parseInt(document.getElementById('countdown').textContent.split(':')[2]);

        if (seconds > 0) {
            seconds--;
        } else {
            if (minutes > 0) {
                minutes--;
                seconds = 59;
            } else {
                if (hours > 0) {
                    hours--;
                    minutes = 59;
                    seconds = 59;
                } else {
                    // Timer has reached zero, you can handle this case as needed
                }
            }
        }

        // Update the timer display
        document.getElementById('countdown').textContent =
            (hours < 10 ? '0' : '') + hours + ' : ' +
            (minutes < 10 ? '0' : '') + minutes + ' : ' +
            (seconds < 10 ? '0' : '') + seconds;
    }

    // Update the timer every second
    setInterval(updateTimer, 1000);
</script>

{% endblock %}

templates/credits.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>{{list_words.credits}}</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/credits.css' %}?v=1.24">
{% endblock%}
<!DOCTYPE html>
{% block container %}

<main class="bg-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
    <div id="cube-icon-container-left" class="left-bg"></div>
    <article>

        <section class="credits-container">

            <h2 class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.credits|upper}}</h2>

            <div class="credits-cards-container card-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">

                {% for profile in profiles %}

                <div class="credits-card content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">

                    <div class="profile-picture_text-container">

                        <img src="{% if profile.picture %}{{profile.picture.url}}{% else %}{% static 'img/default-profile.png' %}{% endif %}" alt="default-picture">

                        <div class="name_role-container">

                            <p class="profile-name text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{profile.user.username}}</p>

                            {% if profile.id == 388 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.graphic_designer}}</p>
                            {% elif profile.id == 6863 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.graphic_designer}}</p>
                            {% elif profile.id == 3267 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.web_designer}}</p>
                            {% elif profile.id == 4509 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.web_animator}}</p>
                            {% elif profile.id == 6861 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.video_editor}}</p>
                            {% elif profile.id == 6894 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.voice_actor}}</p>
                            {% elif profile.id == 529 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.list_translator}} ({{list_words.russian}})</p>
                            {% elif profile.id == 378 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.list_translator}} ({{list_words.german}})</p>
                            {% elif profile.id == 1901 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.list_translator}} ({{list_words.czech}})</p>
                            {% elif profile.id == 5429 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.list_translator}} ({{list_words.turkish}})</p>
                            {% elif profile.id == 2706 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.list_translator}} ({{list_words.danish}})</p>
                            {% elif profile.id == 5522 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.list_translator}} ({{list_words.portuguese}})</p>
                            {% elif profile.id == 5503 %}
                            <p class="profile-rol text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.list_translator}} ({{list_words.french}})</p>
                            {% endif %}

                        </div>

                    </div>

                    <div class="profile-data_social-container">

                        <div class="profile-ranking profile-data">

                            <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.ranking}}</p>

                            <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{profile.position}}</p>

                        </div>

                        <span></span>

                        <div class="profile-nation profile-data">

                            <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.country}}</p>

                            <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
                                <img src="{{profile.country.picture.url}}" alt="country-flag">
                                {% if request.user.is_anonymous %}{{profile.country}}{% elif request.user.profile.language == "English" %}{{profile.country}}{% elif request.user.profile.language == "Spanish" %}{{profile.country.country_spanish}}{% elif request.user.profile.language == "Russian" %}{{profile.country.country_russian}}{% elif request.user.profile.language == "German" %}{{profile.country.country_german}}{% elif request.user.profile.language == "Czech" %}{{profile.country.country_czech}}{% elif request.user.profile.language == "Turkish" %}{{profile.country.country_turkish}}{% elif request.user.profile.language == "Danish" %}{{profile.country.country_danish}}{% elif request.user.profile.language == "Portuguese" %}{{profile.country.country_portuguese}}{% elif request.user.profile.language == "French" %}{{profile.country.country_french}}{% endif %}
                            </p>

                        </div>

                        <span></span>

                        <div class="profile-social profile-data">

                            {% if profile.youtube_channel %}
                            <a href="{{profile.youtube_channel}}"><img src="{% static 'img/youtube-profile-icon.svg' %}" alt="youtube-profile-icon"></a>
                            {% endif %}
                            {% if profile.twitter %}
                            <a href="{{profile.twitter}}"><img src="{% static 'img/twitter-profile-icon.svg' %}" alt="twitter-profile-icon"></a>
                            {% endif %}
                            {% if profile.twitch %}
                            <a href="{{profile.twitch}}"><img src="{% static 'img/twitch-profile-icon.svg' %}" alt="twitch-profile-icon"></a>
                            {% endif %}
                            {% if profile.facebook %}
                            <a href="{{profile.facebook}}"><img src="{% static 'img/facebook-profile-icon.svg' %}" alt="facebook-profile-icon"></a>
                            {% endif %}

                        </div>
                        

                    </div>

                    <a href="{% url 'demonlist:category_or_username' profile.user.username %}" class="view-profile-button button-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
                        {{list_words.view_profile}}
                    </a>

                </div>

                {% endfor %}

            </div>



        </section>

    </article>
    <div id="cube-icon-container-right" class="right-bg"></div>
</main>

{% endblock %}
{% block footer_margin %}100{% endblock  %}

templates/demo_recaptcha.html
<html>
  <head>
    <title>reCAPTCHA demo: Simple page</title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  </head>
  <body>
    <div class="g-recaptcha" data-sitekey="{{key}}" data-callback="correctCaptcha"></div>
<script>
  var correctCaptcha = function(response) {
        console.log(response);
    };
</script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock%}

{% block container %}
    <main>
        <section class="content">
            <h1 class="main-title">Welcome to PlatformerWorld</h1>
            <div class="lists-container">
                <a href="{% url 'demonlist:category_or_username' 'rated' %}" class="list-card">
                    <h2>Rated List</h2>
                    <p>All Platformer Demons list.</p>
                    <span class="view-button">Ver Lista</span>
                </a>
                <a href="{% url 'demonlist:category_or_username' 'unrated' %}" class="list-card">
                    <h2>Unrated List</h2>
                    <p>Unrated levels that are very cool.</p>
                    <span class="view-button">Ver Lista</span>
                </a>
                <a href="{% url 'demonlist:category_or_username' 'challenge' %}" class="list-card">
                    <h2>Tiny List</h2>
                    <p>Levels under 10 seconds.</p>
                    <span class="view-button">Ver Lista</span>
                </a>
            </div>
        </section>
    </main>

    <script src="{% static 'js/home.js' %}"></script>
{% endblock%}

templates/nav.html
{% load static %}

<header>
  <a href="{% url 'demonlist:home' %}" class="logo-container">
      <img src="{% static 'img/logo.webp' %}" alt="Demonlist Logo">
      <span>Home</span>
  </a>
  <nav>
      <a href="{% url 'demonlist:stats_viewer' %}">Stats Viewer</a>
      <a href="{% url 'demonlist:submit_record' %}">Submit Record</a>
      <form method="POST" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit" class="nav-highlight">
          {% if request.user.id %}
          Logout
          {% else %}
          Login
          {% endif %}
        </button>
      </form>
      <button id="adminButton" class="admin-button">
        <i class="fas fa-shield"></i>
        Admin Mode
      </button>
  </nav>
</header>

templates/terms.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>{{list_words.terms_and_conditions}}</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/terms.css' %}?v=1.24">
{% endblock%}
<!DOCTYPE html>
{% block container %}

<main class="bg-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
    <div id="cube-icon-container-left" class="left-bg"></div>
    <article>

        <section class="terms-container">

            <h2 class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.terms_and_conditions|upper}}</h2>

            <div class="main-terms-container">
                <div class="general-container">

                    <ul class="general text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode card-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
                        <p>{{list_words.title_1}}</p>
                        <li class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.text_1}}</li>
                        
                        <p>{{list_words.title_2}}</p>
                        <li class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.text_2}}</li>

                        <p>{{list_words.title_3}}</p>
                        <li class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.text_3}}</li>

                        <p>{{list_words.title_4}}</p>
                        <li class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.text_4}}</li>

                        <p>{{list_words.title_5}}</p>
                        <li class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.text_5}}</li>

                        <p>{{list_words.title_6}}</p>
                        <li class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.text_6}}</li>

                        <p>{{list_words.title_7}}</p>
                        <li class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.text_7}}</li>

                        <p>{{list_words.title_8}}</p>
                        <li class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.text_8}}&nbsp;<a class="discord-server-text" href="https://discord.com/invite/9qwVvCP6rq">{{list_words.discord_server}}</a>.</li>

                    </ul>

                </div>
            </div>


        </section>

    </article>
    <div id="cube-icon-container-right" class="right-bg"></div>
</main>

{% endblock %}
{% block footer_margin %}100{% endblock  %}