PlatformDemonList/urls.py
"""PlatformDemonList URLs module."""

# Django
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.urls import path, re_path, include, reverse_lazy
from django.views.static import serve

# Views
from PlatformDemonList import views
from apps.demonlist.views.views import custom_404_view

# Forms
from apps.users import forms

urlpatterns = [

    path('admin/', admin.site.urls),
    path('ads.txt', serve, {'document_root': settings.BASE_DIR, 'path': 'ads.txt'}),

    path("users/", include(("apps.users.urls", "users"), namespace="users")),
    path('accounts/', include('allauth.urls')),

    re_path(
        route=r'^reset_password/?$',
        view=views.CustomPasswordResetView.as_view(),
        name='reset_password'
    ),
    re_path(
        route=r'^reset_password_sent/?$',
        view=views.CustomPasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    re_path(
        route=r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/?$',
        view=views.CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    re_path(
        route=r'^reset_password_complete/?$',
        view=views.CustomPasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    re_path(
        route=r'^reset_email/?$',
        view=views.CustomEmailResetView.as_view(),
        name='reset_email'
    ),
    re_path(
        route=r'^reset_email_sent/?$',
        view=views.CustomEmailResetDoneView.as_view(),
        name='email_reset_done'
    ),
    re_path(
        route=r'^reset_email/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/?$',
        view=views.CustomEmailResetConfirmView.as_view(),
        name='email_reset_confirm'
    ),
    re_path(
        route=r'^reset_email_complete/?$',
        view=views.CustomEmailResetCompleteView.as_view(),
        name='email_reset_complete'
    ),
    re_path(
        route=r'^terms/?$',
        view=views.TermsView.as_view(),
        name='terms'
    ),

    re_path(
        route=r'^guidelines/?$',
        view=views.GuidelinesView.as_view(),
        name='guidelines'
    ),

    re_path(
        route=r'^credits/?$',
        view=views.CreditsView.as_view(),
        name='credits'
    ),
    re_path(
        route=r'^settings/?$',
        view=views.SettingsView.as_view(),
        name='settings'
    ),

    path('', include(('apps.demonlist.urls', 'demonlist'), namespace='demonlist')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404_view

apps/demonlist/urls.py
"""DemonList URLs."""

# Django
from django.urls import path, re_path

# Views
from apps.demonlist.views import views, views_api
from PlatformDemonList import views as global_views

urlpatterns = [

    path(
        route=r'',
        view=views.HomeView.as_view(),
        name='home'
    ),
    re_path(
        route=r'^vote_stars/(?P<pk>\d+)/?$',
        view=views.VoteStarsView.as_view(),
        name='vote_stars'
    ),
    re_path(
        route=r'^roulette/(?P<pk>\d+)/?$',
        view=views.RouletteView.as_view(),
        name='roulette'
    ),
    re_path(
        route=r'^submit_record/?$',
        view=views.SubmitRecordView.as_view(),
        name='submit_record'
    ),
    re_path(
        route=r'^stats_viewer/?$',
        view=views.StatsViewerView.as_view(),
        name='stats_viewer'
    ),
    re_path(
        route=r'^check_records/?$',
        view=views.CheckRecordsView.as_view(),
        name='check_records'
    ),
    re_path(
        route=r'^check_profiles/?$',
        view=views.CheckProfilesView.as_view(),
        name='check_profiles'
    ),
    re_path(
        route=r'^add_edit_demon/?$',
        view=views.AddEditDemonView.as_view(),
        name='add_edit_demon'
    ),
    re_path(
        route=r'^add_edit_profile/?$',
        view=views.AddEditProfileView.as_view(),
        name='add_edit_profile'
    ),
    re_path(
        route=r'^roulette/?$',
        view=views.CreateRouletteView.as_view(),
        name='create_roulette'
    ),
    re_path(
        route=r'^roulette_menu/?$',
        view=views.RouletteMenuView.as_view(),
        name='roulette_menu'
    ),
    re_path(
        route=r'^diary_role/?$',
        view=views.DiaryRole.as_view(),
        name='diary_role'
    ),
    re_path(
        route=r'^change_language/?$',
        view=views.change_language,
        name='change_language'
    ),

    # API

    re_path(
        route=r'^api/level/?$',
        view=views_api.DemonApi.as_view(),
        name='demon_api'
    ),

    # Rutas con expresión regular

    re_path(
        route=r'^id/(?P<level_id>\d+)/?$',
        view=views.DemonDetailView.as_view(),
        name='level_id_detail'
    ),
    re_path(
        route=r'^(?P<category>\w+)/(?P<position>\d+)/?$',
        view=views.DemonDetailView.as_view(),
        name='detail'
    ),
    re_path(
        route=r'^(?P<category>\w+)/level_packs/?$',
        view=views.LevelPacksView.as_view(),
        name='level_packs'
    ),
    re_path(
        route=r'^(?P<mode>\w+)/(?P<category>\w+)/?$',
        view=views.DemonListView.as_view(),
        name='list'
    ),
    re_path(
        route=r'^(?P<mode>\w+)/(?P<category>\w+)/legacy/?$',
        view=views.DemonListView.as_view(),
        name='list_legacy'
    ),
    re_path(
        route=r'^(?P<mode>\w+)/(?P<category>\w+)/level_packs/?$',
        view=views.LevelPacksView.as_view(),
        name='level_packs'
    ),
    re_path(
        route=r'^(?P<mode>\w+)/(?P<category>\w+)/(?P<position>\d+)/?$',
        view=views.DemonDetailView.as_view(),
        name='detail'
    ),
    re_path(
        route=r'^(?P<value>[^/]+)/?$',
        view=views.CategoryOrUsernameView.as_view(),
        name='category_or_username'
    ),
]

apps/users/urls.py
# Django
from django.urls import path, re_path

# View
from apps.users.views import views, views_discord


urlpatterns = [

    # Management
    re_path(
        route=r'^oauth2/login/?$',
        view=views_discord.discord_login,
        name='discord_login'
    ),
    re_path(
        route=r'^oauth2/login/redirect/?$',
        view=views_discord.DiscordLoginRedirectView.as_view(),
        name='discord_login_redirect'
    ),
    re_path(
        route=r'^update_account/?$',
        view=views_discord.UpdateAccount.as_view(),
        name='update_account'
    ),
    re_path(
        route=r'^demo_recaptcha/?$',
        view=views.demo_recaptcha,
        name='demo_recaptcha'
    ),
    re_path(
        route=r'^read_notifications/?$',
        view=views.ReadNotifications.as_view(),
        name='read_notifications'
    ),
    re_path(
        route=r'^login/?$',
        view=views.LoginView.as_view(),
        name='login'
    ),
    re_path(
        route=r'^logout/?$',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    re_path(
        route=r'^signup/?$',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    re_path(
        route=r'^me/?$',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),
    re_path(
        route=r'^me/teams/?$',
        view=views.TeamsView.as_view(),
        name='teams'
    ),
    re_path(
        route=r'^me/records_status/?$',
        view=views.RecordsStatusView.as_view(),
        name='records_status'
    ),

    # Rutas con expresión regular

    re_path(
        route=r'^(?P<user>\d+)/?$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

apps/users/views/views.py
# Django
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth import authenticate, password_validation
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import connection
from django.db.models import F, Window, Sum, Case, When, CharField, Value, ExpressionWrapper, Func, IntegerField, BooleanField, Q, OuterRef, Subquery, FloatField, Count
from django.db.models.expressions import RawSQL
from django.db.models.functions import Rank, Lag, Lead
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy, resolve, Resolver404, get_resolver
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, FormView, UpdateView, TemplateView
from django.views.generic.base import View
from django_cte import CTEManager, With

# Django REST Framework
from rest_framework import status
from rest_framework.generics import RetrieveAPIView, ListAPIView, UpdateAPIView, GenericAPIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import AccessToken, RefreshToken
from rest_framework_simplejwt.views import TokenObtainPairView

# Mixins
from utils.mixins import CustomMethodsMixin

# Models
from apps.users.models import Profile, Country, Notification, Team, TeamInvitation
from apps.demonlist.models import Demon, Record, Changelog

# Models (Proxy)
from apps.demonlist.models.proxy import ExtendedDemon, ExtendedRecord
from apps.users.models.proxy import ExtendedCountry, ExtendedProfile, ExtendedTeam

# Forms
from apps.users.forms import SignupForm, CustomAuthenticationForm

# Functions and Bot
from apps.demonlist.functions import functions
from apps.users.functions import functions_discord

# Serializers
from apps.demonlist.serializers import DemonModelSerializer, RecordModelSerializer
from apps.users.serializers import UserModelSerializer, ProfileModelSerializer, CountryModelSerializer, ProfileSelect2Serializer, ProfileRouletteModelSerializer, ProfileTeamModelSerializer, TeamModelSerializer, TeamInvitationModelSerializer

# Utils
import ast
import asyncio
import re
from utils.constants import list_choices


def demo_recaptcha(request):
    return render(request, 'demo_recaptcha.html', {
        "key": settings.RECAPTCHA_PUBLIC_KEY
    })


# Vista que marca una notificación como leída
class ReadNotifications(View):

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request):
        notifications = Notification.objects.filter(profile=request.user.profile)
        for notification in notifications:
            notification.read = True
            notification.save()

        response_data = {'success': True,}

        return JsonResponse(response_data)

# Vista de Login
class LoginView(TokenObtainPairView):
    # Login View

    template_name = "users/login.html"
    permission_classes = [AllowAny]

    def get(self, request, *args, **kwargs):
        return Response()

    def post(self, request, *args, **kwargs):
        username = request.data.get('username')
        password = request.data.get('password')
        discord_code = request.data.get("discord_code")  # Discord authorization code

        if discord_code:
            return self.login_with_discord(discord_code)
        
        if username and password:
            return self.login_with_credentials(username, password)

        if '@' in username:
            try:
                user_obj = User.objects.get(email=username)
                username = user_obj.username
            except User.DoesNotExist:
                username = None

        user = authenticate(username=username, password=password)

        if user is not None:
            print(f'Authenticated user: {user.username}')  # Debugging line

            refresh = RefreshToken.for_user(user)
            access_token = str(refresh.access_token)
            refresh_token = str(refresh)
            
            response_data = {
                'refresh': refresh_token,
                'access': access_token,
            }
            response = Response(response_data, status=status.HTTP_200_OK)
            
            if response.status_code == status.HTTP_200_OK:
                response.set_cookie(
                    key='access_token',
                    value=access_token,
                    httponly=True,
                    secure=True,
                    samesite='Lax',
                    max_age=settings.ACCESS_TOKEN_EXPIRATION,  # 1 day
                )
                response.set_cookie(
                    key='refresh_token',
                    value=refresh_token,
                    httponly=True,
                    secure=True,
                    samesite='Lax',
                    max_age=settings.ACCESS_TOKEN_EXPIRATION,  # 1 day
                )
                print(f'Set access_token: {access_token}')  # Debugging line
                print(f'Set refresh_token: {refresh_token}')  # Debugging line

                # Redirect to a specific URL after successful login
                redirect_response = HttpResponseRedirect(reverse_lazy('demonlist:home'))
                redirect_response.set_cookie(
                    key='access_token',
                    value=access_token,
                    httponly=True,
                    secure=True,
                    samesite='Lax',
                    max_age=settings.ACCESS_TOKEN_EXPIRATION,  # 5 minutes
                )
                redirect_response.set_cookie(
                    key='refresh_token',
                    value=refresh_token,
                    httponly=True,
                    secure=True,
                    samesite='Lax',
                    max_age=settings.ACCESS_TOKEN_EXPIRATION,  # 1 day
                )
                if "text/html" in self.request.accepted_media_type:
                    return redirect_response
                else:
                    return response
            else:
                print(f'Error in super() response: {response.status_code}')  # Debugging line
                return response
        else:
            return Response({"detail": "Invalid credentials"}, status=status.HTTP_401_UNAUTHORIZED)

# Vista de Logout
class LogoutView(GenericAPIView):

    def post(self, request):
        try:
            # Obtener el token de refresco del request
            refresh_token = request.COOKIES.get('refresh_token')
            if refresh_token:
                # Invalidar el token de refresco
                token = RefreshToken(refresh_token)
                token.blacklist()
                print(f"Refresh token invalidated: {refresh_token}")  # Debugging line
        except Exception as e:
            print(f"Error invalidating token: {e}")  # Debugging line

        # Crear la respuesta y eliminar las cookies
        if "text/html" in self.request.headers.get('Accept'):
            response = HttpResponseRedirect(reverse_lazy('users:login'))  # Redirigir al login
        else:
            response = JsonResponse({"message": "Logout success!"}, safe=False)  # Mostrar deslogueo exitoso
        response.delete_cookie('access_token', path='/', domain=None)
        response.delete_cookie('refresh_token', path='/', domain=None)
        print("Cookies deleted and user redirected to login")  # Debugging line
        return response

# Vista para Registrarse
class SignupView(APIView):
    # Users sign up view

    template_name = "users/signup.html"

    def get_context_data(self, **kwargs):
        form = SignupForm()

        context = {}
        if "text/html" in self.request.accepted_media_type:
            context["form"] = form

        context["help_text"] = password_validation.password_validators_help_text_html()
        return context
    
    def get(self, request, *args, **kwargs):
        """Método Get: Habilita el método Get a la vista."""
        context = self.get_context_data()
        return Response(context)

    def post(self, request, *args, **kwargs):
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Optional: You can log in the user directly after signup or send a confirmation email
            if self.request.accepted_renderer.media_type == "text/html":
                return HttpResponseRedirect(reverse_lazy('users:login'))
            else:
                return Response({'detail': 'User created successfully'}, status=status.HTTP_201_CREATED)
        else:
            if self.request.accepted_renderer.media_type == "text/html":
                return Response({'form': form}, template_name=self.template_name)
            else:
                return Response({'errors': form.errors}, status=status.HTTP_400_BAD_REQUEST)


# Vista para Editar tu Perfil
class UpdateProfileView(CustomMethodsMixin, GenericAPIView):
    template_name = 'users/update_profile.html'
    serializer_class = CountryModelSerializer

    permission_classes = [IsAuthenticated]

    # DATA (GET)
    def get_data(self):
        """Obtiene los datos del contexto de la solicitud GET."""
        return {
            "records": self.get_records(),
            "device": self.get_device(),

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PlatformerWorld</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <!-- Add Sortable.js -->
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"></script>
</head>

<body>
    <canvas id="particleCanvas"></canvas>

    {% include "nav.html" %}

    {% block container %}
    {% endblock%}

    <footer>
        <p>&copy; 2024 PlatformerWorld - Creado por Chenii y el Chucky</p>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/users/login.html
{% extends 'users/base.html' %}
{% load socialaccount %}
{% load static %}

{% block head_content %}
<title>Login | Platformer World</title>
<link rel="stylesheet" href="{% static 'css/cuenta.css' %}?v=1.24">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
{% endblock %}


{% block container %}

    <!-- Particle Background -->
    <div id="particles"></div>
    <div class="aurora-container">
        <div class="aurora-1"></div>
        <div class="aurora-2"></div>
        <div class="aurora-3"></div>
        <div class="aurora-4"></div>
    </div>

    <!-- Login and Register Forms -->
    <div class="div-login-container">
        <div class="forms-container">
            <!-- Login Form -->
            <div class="form-section login">
                <h2>Welcome Back</h2>
                <p>Enter your credentials to access your account</p>

                <form method="POST" action="{% url "users:login" %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="username" id="username" required>
                        <label>Username/Email</label>
                        <span class="highlight"></span>
                    </div>

                    <div class="input-group">
                        <input type="password" type="password" name="password" id="password" required>
                        <label>Password</label>
                        <span class="highlight"></span>
                    </div>

                    <div class="options">
                        <a href="#" class="forgot">Forgot Password?</a>
                    </div>

                    <button type="submit" class="submit-btn">Sign In</button>
                </form>

                <p class="toggle-text">
                    Don't have an account? 
                    <a href="#" class="toggle-btn">Sign Up</a>
                </p>
            </div>

            <!-- Register Form -->
            <div class="form-section register">
                <h2>Create Account</h2>
                <p>Join us today and start your journey</p>

                <form action="{% url "users:signup" %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" id="username" name="username" required>
                        <label>Full Name</label>
                        <span class="highlight"></span>
                    </div>

                    <div class="input-group">
                        <input type="email" id="email" name="email" required>
                        <label>Email Address</label>
                        <span class="highlight"></span>
                    </div>

                    <div class="input-group">
                        <input type="password" id="password" name="password" required>
                        <label>Password</label>
                        <span class="highlight"></span>
                    </div>

                    <div class="input-group">
                        <input type="password" id="password_confirmation" name="password_confirmation" required>
                        <label>Confirm Password</label>
                        <span class="highlight"></span>
                    </div>

                    <label class="terms">
                        <input type="checkbox" required>
                        <span>I agree to the Terms of Service and Privacy Policy</span>
                    </label>

                    <button type="submit" class="submit-btn">Create Account</button>
                </form>

                <p class="toggle-text">
                    Already have an account? 
                    <a href="#" class="toggle-btn">Sign In</a>
                </p>
            </div>
        </div>
    </div>

    <!-- JavaScript for Particles and Form Toggle -->
    <script>
        // Particle animation
        const particlesContainer = document.getElementById('particles');
        const particleCount = 50;

        for (let i = 0; i < particleCount; i++) {
            const particle = document.createElement('div');
            particle.className = 'particle';
            particle.style.setProperty('--x', `${Math.random() * 100}%`);
            particle.style.setProperty('--y', `${Math.random() * 100}%`);
            particle.style.setProperty('--duration', `${10 + Math.random() * 20}s`);
            particle.style.setProperty('--delay', `${-Math.random() * 20}s`);
            particlesContainer.appendChild(particle);
        }

        // Form toggle
        document.querySelectorAll('.toggle-btn').forEach(button => {
            button.addEventListener('click', (e) => {
                e.preventDefault();
                document.querySelector('.forms-container').classList.toggle('show-register');
            });
        });

        // Interactive background effect
        document.addEventListener('mousemove', (e) => {
            const { clientX, clientY } = e;
            const x = Math.round((clientX / window.innerWidth) * 100);
            const y = Math.round((clientY / window.innerHeight) * 100);

            document.documentElement.style.setProperty('--mouse-x', `${x}%`);
            document.documentElement.style.setProperty('--mouse-y', `${y}%`);
        });
    </script>

{% endblock%}

templates/users/records_status.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>{{list_words.records_status}}</title>
<link rel="stylesheet" href="{% static 'css/records_status.css' %}?v=1.24" />
{% endblock %}

{% block container %}

<main class="bg-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">

    <div id="cube-icon-container-left" class="left-bg"></div>
    <article>

        <section class="records-status-container">

            <h2 class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{{list_words.records_status|upper}}</h2>

            <table class="records-table card-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
                <thead>
                  <tr class="records-header card-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
                    <th>{{list_words.demon}}</th>
                    <th>{{list_words.video_proof}}</th>
                    <th>{{list_words.status}}</th>
                    <th>{{list_words.mod_notes}}</th>
                    <th>{{list_words.rating_stars}}</th>
                  </tr>
                </thead>
                <tbody>
                  {% if records %}
                  {% for record in records %}
                  <tr class="records-body">
                    <td class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode"><a class="demon-link text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode" href="{% url 'demonlist:level_id_detail' record.demon.level_id %}"> {{record.demon}}</td>
                    <td class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
                      {% if record.video_platform == "Drive" %}
                      <a href="{{ record.video }}" class="drive-button">
                          Drive
                          <img src="{% static 'img/drive-icon--table.svg' %}" alt="drive-icon">
                      </a>
                      {% elif record.video_platform == "Facebook" %}
                      <a href="{{ record.video }}" class="facebook-button">
                          Facebook
                          <img src="{% static 'img/facebook-icon--table.svg' %}" alt="facebook-icon">
                      </a>
                      {% elif record.video_platform == "YouTube" %}
                      <a href="{{ record.video }}" class="youtube-button">
                          YouTube
                          <img src="{% static 'img/youtube-icon--table.svg' %}" alt="youtube-icon">
                      </a>
                      {% elif record.video_platform == "Twitch" %}
                      <a href="{{ record.video }}" class="twitch-button">
                          Twitch
                          <img src="{% static 'img/twitch-icon--table.svg' %}" alt="twitch-icon">
                      </a>
                      {% else %}
                      {% endif %}
                    </td>
                    <td class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
                      {% if record.accepted %}
                      <i class="fas fa-check-circle" style="font-size: 24px; color: green;"></i>
                      {% elif record.under_consideration %}
                      <i class="fas fa-clock" style="font-size: 24px; color: #176ee0;"></i>
                      {% elif record.accepted is none %}
                      <i class="fas fa-clock" style="font-size: 24px; color: gray;"></i>
                      {% else %}
                      <i class="fas fa-times-circle" style="font-size: 24px; color: red;"></i>
                      {% endif %}
                    </td>
                    <td class="content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">{% if record.mod_notes and record.mod_notes != "None" %}{{record.mod_notes}}{% else %}-{% endif %}</td>
                    <td class="rating-stars-container content-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
                      {% if record.accepted %}
                        <a class="demon-link text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode" href="{% url 'demonlist:vote_stars' record.id %}">{{list_words.vote}}</a>
                        {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                  {% endif %}

                </tbody>
            </table>
              

        </section>

    </article>
    <div id="cube-icon-container-right" class="right-bg"></div>

</main>

<script>
    function updateYoutubeValue(input) {
        const userValue = input.value.substring("https://www.youtube.com/@".length);
    
        input.value = "https://www.youtube.com/@" + userValue;
      }
      function updateTwitterValue(input) {
        const userValue = input.value.substring("https://twitter.com/".length);
    
        input.value = "https://twitter.com/" + userValue;
      }
      function updateTwitchValue(input) {
        const userValue = input.value.substring("https://twitch.tv/".length);
    
        input.value = "https://twitch.tv/" + userValue;
      }
      function updateFacebookValue(input) {
        const userValue = input.value.substring("https://facebook.com/".length);
    
        input.value = "https://facebook.com/" + userValue;
      }
</script>
{% endblock %}

{% block footer_margin %}600{% endblock %}

templates/users/signup.html
{% extends 'users/base.html' %}
{% load static %}

{% block head_content %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}?v=1.24">
{% endblock %}

{% block container %}

    <form class="signup-form text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode" action="{% url "users:signup" %}" method="POST">
        {% csrf_token %}

        {% if form.errors.1 %}
            <p class="login-text text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode"><i class="fas fa-exclamation-triangle"></i> {{form.errors.1}}</p>
        {% endif %}

        {{form}}

        {{help_text}}
        
        <p class="text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">Do you have an account? <a href="{% url 'users:login' %}" class="alt-text-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">Log in here</a></p>

        <button type="submit" class="signup-button main-button-{% if request.global_context.dark_mode %}dark{% else %}light{% endif %}mode">
            Register!
        </button>

    </form>

    <script>

        function without_space(e) {
            e.value = e.value.replace(/ /g, '').replace(/\//g, '');
        }
    </script>
{% endblock%}